{% set name = "centerline" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/centerline-{{ version }}.tar.gz
  sha256: 1bec56126b786a2991d5bd84bf8b3f26e12d12cc50c5d77a28fd6af5866240a9

build:
  entry_points:
    - create_centerlines = centerline.converters:create_centerlines
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - certifi
    - click >=7.0
    - fiona >=1.7.0
    - numpy >=1.10.4
    - python >=3.6
    - scipy >=0.16.1
    - shapely >=1.5.13

test:
  imports:
    - centerline
  commands:
    - pip check
    - create_centerlines --help
  requires:
    - pip

about:
  home: https://github.com/fitodic/centerline
  summary: Calculate the centerline of a polygon
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
